imagesAzureProject/imagesAzureProject/Models/Image.cs
using System.ComponentModel.DataAnnotations;

namespace imagesAzureProject.Models
{
    public class Image {
        /// <summary>
        /// The Id of the entity
        /// </summary>
        /// 
        public int Id { get; set; }

        /// <summary>
        /// The name of the image. It can be different than actual file name.
        /// </summary>

         public string Name { get; set; }

        /// <summary>
        /// The description of the image
        /// </summary>
        public string Description { get; set; }

        /// <summary>
        /// The path the actual image is stored (normally the blob storage reference)
        /// </summary>
        /// 
       
        public string ImagePath { get; set; }
    }
}

imagesAzureProject/imagesAzureProject/Models/ImagesContext.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;

namespace imagesAzureProject.Models
{
        public class ImagesContext : DbContext
        {
            public ImagesContext() : base("name=imageconnectionstring")
            {
                Database.SetInitializer<ImagesContext>(new DropCreateDatabaseIfModelChanges<ImagesContext>());
            }
            public DbSet<Image> Images { get; set; }
        }
}

imagesAzureProject/imagesAzureProject/Controllers/HomeController.cs
using imagesAzureProject.Models;
using ImagesAzureProject.Repositories;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace imagesAzureProject.Controllers
{
    public class HomeController : Controller
    {

        // Declare a variable for an object that implements the IImagesService interface
        private IImagesService imageRepository;

        // Allows the caller pass a context instance
        public HomeController(IImagesService ImageRepository)
        {
            this.imageRepository = ImageRepository;
        }

        // GET: Home
        public ActionResult Index()
        {         
            return View(imageRepository.GetImages());
        }
    }
}

imagesAzureProject/imagesAzureProject/Controllers/ImagesController.cs
using imagesAzureProject.Models;
using ImagesAzureProject.Repositories;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Mvc;

namespace imagesAzureProject.Controllers
{
    public class ImagesController : Controller
    {

        private IImagesService imageRepository;
        private IAzureStorage AzureStorage;

        //Injected the Repositories
        public ImagesController(IImagesService ImageRepository, IAzureStorage AzureStorage)
        {
            this.imageRepository = ImageRepository;
            this.AzureStorage = AzureStorage;
        }

        public ActionResult AddImage()
        {
            return View();
        }

        public ActionResult DeleteImage(int? id)
        {          
            //Find the Image
            Image currentImage = imageRepository.GetImages().Where(x => x.Id == id).FirstOrDefault();
            
            //Check if Exist
            if (currentImage ==null)
                 return RedirectToAction("Index", "Home");


            return View(currentImage);
        }
 
        public ActionResult Details(int? id)
        {
            //Find the Image
            Image currentImage = imageRepository.GetImages().Where(x => x.Id == id).FirstOrDefault();

            //Check if Exist
            if (currentImage == null)
                return RedirectToAction("Index", "Home");


            return View(currentImage);
        }


        //Get Name and Description
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult AddImage([Bind(Include = "Name,Description")] Image image)
        {
            //Validate Model 
            if (ModelState.IsValid)
            {
                    // Get first file
                    var newImage = Request.Files[0];

                    string errorMsg = "";

                if (!isValidName(image, ref errorMsg))
                {
                    ModelState.AddModelError("Name", errorMsg);
                    return View();
                }


                    //Check if file is Valid Image
                    if (isValidImage(newImage, ref errorMsg))
                {

                    //Upload Image to Azure               
                    Image UploadedImage = AzureStorage.UploadImage(newImage, image);

                    // Set Image Path
                    image.ImagePath = UploadedImage.ImagePath;

                    //Add Image to DB
                    int id = imageRepository.AddNewImage(image);

                    TempData["Success"] = "The image was added successfully";
                }
                else
                    ModelState.AddModelError("ImagePath", errorMsg);                          
            }
            return View();
        }

        //Get Image and Delete it
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteImage([Bind(Include = "Id")] int Id)
        {
            Image currentImage = imageRepository.GetImages().Where(x => x.Id == Id).FirstOrDefault();

            //Delete from Azure Storage
            bool Deleted = AzureStorage.DeleteImage(currentImage);

            // Delete current Image
            if (Deleted)
            imageRepository.DeleteImage(Id);

            TempData["SuccessfulDelete"] = "Successfully Deleted";
            return RedirectToAction("Index", "Home"); ;
        }


        // Validate Name
        private bool isValidName(Image image, ref string errorMsg)
        {
            if (image.Name == null)
            {
                errorMsg = "Please enter Image Name.";
                return false;
            }
          

            Regex r = new Regex(@"^[_a-zA-Z0-9]*$");
            Match match = r.Match(image.Name);
            if (!match.Success)
            {
                errorMsg = "Please enter a valid Name.Only alphanumeric Characters or _ !";
                return false;
            }

            return true;
        }

    // Check if is a Valid Image
    private bool isValidImage(HttpPostedFileBase InputFile, ref string errorMsg)
        {
            // Check if is Null or 0 Kb
            if (InputFile == null || InputFile.ContentLength == 0)
            {
                //Add error to Model
                errorMsg = "Error! Please select Image file !";
                return false;
            }

            try
            {
                //Images extensions . We could add every extension we want 
                string[] imagesExtensions = { ".jpg", ".png" };

                // Cehck if file is .png or .jpg
                if (imagesExtensions.Contains(Path.GetExtension(InputFile.FileName)))
                {
                    // Check if file is Image File
                    System.Drawing.Image imgInput = System.Drawing.Image.FromFile(InputFile.FileName);
                    System.Drawing.Imaging.ImageFormat thisFormat = imgInput.RawFormat;
                }
                else
                {
                    errorMsg = "Error! Accept only .jpg and .png files!";
                    return false;
                }
            }
            catch
            {
                errorMsg = "Error! This file is not Image!";
                return false;
            }

            return true;

        }
    }
}

imagesAzureProject/imagesAzureProject/Views/Home/Index.cshtml
@model IEnumerable<imagesAzureProject.Models.Image>

@{
    ViewBag.Title = "Home";
}

<h2>Index</h2>
<div class="form-horizontal">
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @if (TempData["SuccessfulDelete"] != null)
    {
        <div class="green">
            <p style="color:lightgreen"><strong>Success:</strong> @TempData["SuccessfulDelete"].ToString()</p>
        </div>
    }
    </div>
    <p>
        @Html.ActionLink("Upload New", "AddImage", "Images")
    </p>
    <table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Description)
            </th>
            <th>
                @Html.Label("Image")
            </th>
            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Description)
                </td>
                <td>
                    <img src="@Html.DisplayFor(modelItem => item.ImagePath)" width="200" height="130" />
                </td>
                <td>
                    @Html.ActionLink("Details", "Details", "Images", new { id = item.Id }, null) | 
                    @Html.ActionLink("Delete", "DeleteImage", "Images", new { id = item.Id }, null)
                </td>
            </tr>
        }

    </table>

imagesAzureProject/imagesAzureProject/Views/Images/AddImage.cshtml
@model imagesAzureProject.Models.Image

@{
    ViewBag.Title = "Add New Image";
}

<h2>Add New Image</h2>

@using (Html.BeginForm("AddImage", "Images", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Image</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @if (TempData["Success"] != null)
        {
            <div class="green">
                 <p style="color:lightgreen"><strong>Success:</strong> @TempData["Success"].ToString()</p>
            </div>
        }
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Description, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("Select Image", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="newImage" name="newImage" type="file" class="form-control" />
                @Html.ValidationMessageFor(model => model.ImagePath, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Upload" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index","Home")
</div>

<script src="~/Scripts/jquery-1.10.2.min.js"></script>
<script src="~/Scripts/jquery.validate.min.js"></script>
<script src="~/Scripts/jquery.validate.unobtrusive.min.js"></script>

imagesAzureProject/imagesAzureProject/Views/Images/DeleteImage.cshtml
@model imagesAzureProject.Models.Image

@{
    ViewBag.Title = "Delete Image";
}

<h2>Delete Image</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.Label("Image")
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.ImagePath)" width="200" height="130" />
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index", "Home")
        </div>
    }
</div>

imagesAzureProject/imagesAzureProject/Views/Images/Details.cshtml
@model imagesAzureProject.Models.Image

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Image</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Description)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Description)
        </dd>

        <dt>
            @Html.Label("Image")
        </dt>

        <dd>
            <img src="@Html.DisplayFor(model => model.ImagePath)" width="200" height="130" />
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Back to List", "Index", "Home")
</p>

imagesAzureProject/imagesAzureProject/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - Azure Images Project</title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Azure Images Project", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - AzureImagesProject</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>